### ISSUE TITLE
General notes in your app 

### ISSUE THREAD

**Issue by AhmedQeshta** [GSG-G11/Mustafa-Najlaa-autocomplete#8]
### General Notes in Your app 🚀👨🏻‍💻👨🏻‍💻

In the beginning, you did a very **nice job** 💖 so I applaud you for it.
But there are some beautiful notes to make your application more beautiful and beautiful, and its effectiveness greater.

- The **`datalist`** country is duplicating every time we search
- **` No error `** handling
- You **` haven't used abstraction `** on any of your code,
   - [First One](https://github.com/GSG-G11/Mustafa-Najlaa-autocomplete/blob/7d2ca649ebe567a073cf7f02adef6fabfba62dab/src/router.js#L11)
   - [second one](https://github.com/GSG-G11/Mustafa-Najlaa-autocomplete/blob/7d2ca649ebe567a073cf7f02adef6fabfba62dab/src/router.js#L22)
   -  [Third one](https://github.com/GSG-G11/Mustafa-Najlaa-autocomplete/blob/7d2ca649ebe567a073cf7f02adef6fabfba62dab/src/router.js#L33)
   - [Forth one](https://github.com/GSG-G11/Mustafa-Najlaa-autocomplete/blob/7d2ca649ebe567a073cf7f02adef6fabfba62dab/src/router.js#L44)
_And to the end of this file_   [here](https://github.com/GSG-G11/Mustafa-Najlaa-autocomplete/blob/7d2ca649ebe567a073cf7f02adef6fabfba62dab/src/router.js)

- The **` js file `** must be refactored, [here](https://github.com/GSG-G11/Mustafa-Najlaa-autocomplete/blob/7d2ca649ebe567a073cf7f02adef6fabfba62dab/public/js/main.js)

- There is some commented code, [here](https://github.com/GSG-G11/Mustafa-Najlaa-autocomplete/blob/7d2ca649ebe567a073cf7f02adef6fabfba62dab/public/js/main.js#L50).

- You should take care more of your CSS

- You pushed the readme file directly from the main   

- The Heroku doesn't have the same deployment on GitHub

**Comment by EngNajlaa** [comment]
What do you mean The Heroku doesn't have the same deployment on GitHub؟

**Comment by AhmedQeshta** [comment]
My project partner. He told me that you did not upload the project on Heroku. In the latest version on GitHub, you should click like in the **picture**

![image](https://user-images.githubusercontent.com/38624002/155483298-6e2e3e2a-cf0c-43c8-be1c-00e6417bee84.png)
